apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Tempo
    orgId: 1
  - name: Loki
    orgId: 1

datasources:
    - name: Prometheus
      type: prometheus
      uid: prometheus
      access: proxy
      url: http://prometheus:9090
      isDefault: true
      editable: true

    - name: Tempo
      type: tempo
      access: proxy
      url: http://tempo:3200
      uid: tempo
      jsonData:
        httpMethod: GET
        tracesToLogsV2:
          datasourceUid: loki
          spanStartTimeShift: "-1h"
          spanEndTimeShift: "1h"
          filterByTraceID: false
          filterBySpanID: false
          customQuery: true
          query: '{$${__tags}} | traceID = `$${__span.traceId}`'
          tags:
            - key: service.name
              value: service_name
        tracesToMetrics:
          datasourceUid: prometheus
          spanStartTimeShift: "-1h"
          spanEndTimeShift: "1h"
          tags:
            - key: service.name
              value: exported_service_name
        serviceMap:
          datasourceUid: prometheus
        nodeGraph:
          enabled: true

    - name: Loki
      type: loki
      access: proxy
      url: http://loki:3100
      uid: loki
      jsonData:
        derivedFields:
          - name: traceID
            datasourceUid: tempo
            matcherRegex: "trace_id"
            matcherType: label
            url: "$${__value.raw}"
          - name: traceID
            datasourceUid: tempo
            matcherRegex: "traceID"
            matcherType: label
            url: "$${__value.raw}"
